# The path of the sentence pair path you downloaded from Tatoeba 
sentence_pairs_path = "Satzpaare Tschechisch-Deutsch - 2022-05-30.tsv"
# The source language of the sentence pairs (the language you want to learn)
# Use IETF language tag, for example "es" would be Spanish
source_language = "cs"
# The maximum number of sentences you want to include in the dataset.
# It will by default prefer sentences that have native Tatoeba audio, then it will delete sentences at random 
# (preferring to delete duplicates)
max_sentence_number = 10000
sentences_with_audio_path = "sentences_with_audio.tar.bz2"
# Audi download mode: How do you want to download the audio files?
# "Both" - download audio from Tatoeba, if not available, then use Google-TTS
# "Tatoeba" - download audio only from Tatoeba
# "Google" - download audio only from Google-TTS
# "None" - do not download audio
download_mode = "Both"
# Wait interval between each sentence audio download (in seconds)
# This reduces the load on the Tatoeba servers and the chance you get blocked by Google, but
# reducing it will increase performance
wait_interval = 1.5
# The name of the generated deck
deck_name = "Tatoeba-Deutsch-Tschechisch-New"
# The description of the generated deck, displayed in Anki
deck_description = "A deck which contains more than 5000 sentences from Czech to German. The sentences are taken from Tatoeba.com. Tschechisch-Deutsch"
# The output path of the generated deck
deck_output_path = "Tatoeba-Deutsch-Tschechisch new.apkg"
# Unique IDs of the generated deck/model
# According to genanki, should be generated using 
# import random; random.randrange(1 << 30, 1 << 31)
# and then written here
model_id = 1524505956
deck_id = 1329331698
# Should there be help included to look up single words?
# "None" - cards only contain sentences
# "Wiktionary" - cards contain links to Wiktionary
# "Dictionary" - use a custom dictionary to directly include single word definitions on the cards.
single_word_lookup_mode = "Dictionary"
wiktionary_base_url = "https://en.wiktionary.org/wiki/"
# The wiktionary language that should be linked to - if you use the Spanish Wiktionary this should be in Spanish, for example
wiktionary_source_language = "Czech" 
# Dictionary file path - If you want to use a custom dictionary to include direct translations of each word in the sentence,
# you can specify the path to the file here. Note that the file should be in the Tabfile format.
# If you have a dictionary in another format, convert it using https://github.com/ilius/pyglossary
# If you do not want to use a custom dictionary, set this field to "None"
dictionary_path = "Tschechisch-Deutsch.txt"